name: cdk-ci

on:
  # push:
  #   branches: ["main"]
  #   paths-ignore: ['app/**']
  pull_request:
    branches: ["main"]
    paths-ignore: ["app/**"]

jobs:
  cdk_ci:
    name: "CDK CI"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Setup dependencies
        run: npm ci

      - name: Unit tests
        run: npm run test

      - name: CDK Diff Check
        run: npm run cdk diff
        env:
          AWS_DEFAULT_REGION: "ap-northeast-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
